# Generated by Django 3.2.7 on 2021-09-18 12:52

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('origem', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'marca',
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
