# Generated by Django 3.2.7 on 2021-09-18 12:52

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('km_por_galao', models.FloatField(null=True)),
                ('cilindros', models.SmallIntegerField()),
                ('cavalo_de_forca', models.SmallIntegerField()),
                ('peso', models.FloatField()),
                ('aceleracao', models.FloatField(null=True)),
                ('ano', models.DateField()),
                ('origem', models.CharField(max_length=20)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marca', to='marca.marca')),
            ],
            options={
                'db_table': 'carro',
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
